# ============================================
# logging
# ============================================
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    compress: "true"
# ============================================
# netwokrs
# ============================================
networks:
  restricted_wan:
    external: true
  internal_immich:
    driver: bridge
# ============================================
# secrets
# ============================================
secrets:
  postgres_user:
    file: ${SECRETS}/pg_user
  postgres_password:
    file: ${SECRETS}/pg_pas

services:
  # ============================================
  # immich - photos
  # ============================================
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    logging: *default-logging
    hostname: immich-server
    secrets:
      - postgres_password
      - postgres_user
    networks:
      internal_immich:
      restricted_wan:
        ipv4_address: 172.20.30.80
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy
      immich-machine-learning:
        condition: service_healthy
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    environment:
      - LOG_LEVEL=info
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=${USER_MASK}
      - DB_HOSTNAME=immich_postgres
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
      - DB_USERNAME_FILE=/run/secrets/postgres_user
      - REDIS_HOSTNAME=immich_redis
      - IMMICH_MACHINE_LEARNING_HOST=immich-machine-learning
    volumes:
      - ${UPLOAD_LOCATION}:/data:rw
      - ${EXTERNAL_LIB_1}:/external_photos:ro
      - ${EXTERNAL_LIB_2}:/external_photos_1:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=cloudflare"
      - "traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "2"
  # ============================================
  # ml
  # ============================================
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    logging: *default-logging
    hostname: immich-machine-learning
    networks:
      - internal_immich
    volumes:
      - ${UPLOAD_LOCATION}:/data:rw
      - ${CONFIG_ROOT:-.}/immich/cache:/cache:rw
      - ${CONFIG_ROOT:-.}/immich/cache:/.cache:rw
      - ${CONFIG_ROOT:-.}/immich/cache:/.config:rw
      - ${CONFIG_ROOT:-.}/immich/matplotlib:/matplotlib:rw
    environment:
      - LOG_LEVEL=info
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=${USER_MASK}
      - MPLCONFIGDIR=/matplotlib
      - TRANSFORMERS_CACHE=/cache/huggingface
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=false"
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: "2"
  # ============================================
  # redis - cache
  # ============================================
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    hostname: immich_redis
    logging: *default-logging
    networks:
      - internal_immich
    environment:
      - LOG_LEVEL=info
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=${USER_MASK}
    volumes:
      - ${CONFIG_ROOT:-.}/redis/immich:/data:rw
    labels:
      - "traefik.enable=false"
    security_opt:
      - no-new-privileges:true
    restart: "unless-stopped"
    healthcheck:
      test: redis-cli ping || exit 1
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
  # ============================================
  # postgres - db
  # ============================================
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    hostname: immich_postgres
    secrets:
      - postgres_password
      - postgres_user
    networks:
      - internal_immich
    environment:
      - LOG_LEVEL=info
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TIMEZONE}
      - UMASK_SET=${USER_MASK}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - DB_STORAGE_TYPE=HDD
    volumes:
      - ${CONFIG_ROOT:-.}/postgres/immich:/var/lib/postgresql/data:rw
    labels:
      - "traefik.enable=false"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user)"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
